app = "gib878-sniper-flyio-v2"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  NODE_ENV = "production"
  PORT = "3000"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
