name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          api_token: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only 
